[package]
name = "pubsub_rustexpensivecode"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "pubsub_rustexpensivecode"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"
